### PR TITLE
Loads of Enhancements

### PR DESCRIPTION
**Pull request by bitsol**
Added logo to form.
Created an open on startup option.
Added assembly information (feel free to change it).
Created an "always on top" window.
Changed the location of content.csv to be in the Debug folder (it's no longer included in the repo).

### CODE REVIEW

**Comment by MrCull** [comment]
Nice work bitsol although i fear you are wasting your time.
I submitted a few pull requests a while back and did not get any response :-(

In the end I created a separate fork of this and started developing on top of that.

Feel free to submit your PRs to my fork if you want an I'll maintain that until there is some life back here.

**Comment by ralphite** [comment]
@bitsol @MrCull Thanks so much for the PR. I actually do not have a Windows machine now. I'll find one this week and verify the changes.

**Comment by bitsol** [comment]
Thanks guys!

**Comment by bitsol** [comment]
@ralphite Should I continue to submit pull requests to this repo or the fork by @MrCull?

**Comment by bitsol** [comment]
Once @ralphite gets a Windows machine and accepts this PR and all of the PRs submitted by @MrCull, I'll submit my PRs on this repository.

**Comment by MrCull** [comment]
Woot woot I use this app most days at work so will be great to get this progressing again!
Take a look at my fork and let me know which changes you would like submitting here @ralphite

**Comment by MrCull** [comment]
Any news on this 😉

**Comment by bitsol** [comment]
@ralphite Could you accept the PR? It's been a while.

**Comment by MrCull** [comment]
@ralphite if you would like someone else to help you maintain this reop then I'd be happy to help out or even take ownership if you prefer?

**Comment by ralphite** [comment]
@MrCull @bitsol Thanks for the offer! I'm sorry I didn't have enough time to work on this.

**Comment by MrCull** [comment]
Thanks @ralphite I've merged in a few pull requests.
If you have any more ideas for this App then raise some issues and I (or maybe @bitsol?) will have a go at implementing them.

@bitsol - if you dont have "contributor" access to this repo then, if you want to submit a new PR for these changes based on the current master then i'll merge them in.
Also a few issues have been logged if you, or anyone else is looking for a little more work ;-)

**Comment by bitsol** [comment]
Never mind! These conflicts will just complicate things. Let's start fresh with adding new features.

**Pull request closed without merging**
